export { default as CoreLayout } from './CoreLayout/CoreLayout';
export { default as SectionLayout } from './SectionLayout/SectionLayout';
export { default as Header } from './Header/Header';
export { default as Footer } from './Footer/Footer';
export { default as FrontPage } from './Pages/FrontPage/FrontPage';
export { default as Services } from './Pages/Services/Services';
export { default as About } from './Pages/About/About';
export { default as Works } from './Pages/Works/Works';
export { default as Careers } from './Pages/Careers/Careers';