export { default as Hero } from './Hero/Hero';
export { default as About } from './About/About';
export { default as Dream } from './Dream/Dream';
export { default as Consultation } from './Consultation/Consultation';
export { default as Services } from './Services/Services';
export { default as BusinessPlatform } from './BusinessPlatform/BusinessPlatform';
export { default as Projects } from './Projects/Projects';
export { default as Phrase } from './Phrase/Phrase';
export { default as Technologies } from './Technologies/Technologies';